### ISSUE TITLE
Odk collect conflict 

### ISSUE THREAD

**Issue by dalekunce** [GeoODK/GeoODK-Software-Package-#1]
If you have both odk collect and geoodk on a phone forms completed in odk collect cannot be sent using odk. They are moved to geoodk for some reason, where they cannot be sent without changing geoodk aggregate server settings.

**Comment by GeoODK** [comment]
This issues is meant for the collect application not the software package. I have moved the issue to collect repo (https://github.com/GeoODK/collect/issues/9 ). Also I have fixed the issue and will be push and update to the app store later today. https://github.com/GeoODK/collect/commit/c48aad7903e35f38af0206e76507aa7831c0da70

**Comment by dalekunce** [comment]
Last time I try and fill an issue from my phone. Thanks
